/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ebe7e9",
        "secondary": "#5f5e5e",
        "surface-variant": "#e5e1e3",
        "surface": "#fcf8fa",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#474646",
        "tertiary-container": "#c5eed9",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "on-surface": "#1c1b1d",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#313032",
        "inverse-on-surface": "#f4f0f2",
        "on-surface-variant": "#47464d",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e5e1e3",
        "on-primary-container": "#66647c",
        "secondary-fixed": "#e5e2e1",
        "surface-bright": "#fcf8fa",
        "on-secondary-container": "#656464",
        "on-primary-fixed": "#1a192e",
        "surface-container-low": "#f7f2f5",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002115",
        "secondary-fixed-dim": "#c8c6c5",
        "error": "#ba1a1a",
        "primary": "#5e5c74",
        "secondary-container": "#e5e2e1",
        "on-primary-fixed-variant": "#46445b",
        "on-tertiary-fixed-variant": "#294e3f",
        "on-background": "#1c1b1d",
        "tertiary": "#416656",
        "inverse-primary": "#c7c3df",
        "background": "#fcf8fa",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#a8cfbc",
        "on-tertiary-container": "#496d5d",
        "outline-variant": "#c8c5cd",
        "primary-container": "#e6e2ff",
        "outline": "#78767d",
        "surface-dim": "#ddd9db",
        "primary-fixed-dim": "#c7c3df",
        "surface-container": "#f1edef",
        "surface-tint": "#5e5c74",
        "primary-fixed": "#e3dffc",
        "tertiary-fixed": "#c3ecd7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "stack-md": "1.5rem",
        "gutter": "2rem",
        "section-padding": "8rem",
        "container-max": "1200px",
        "stack-lg": "3rem"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}